In [1]:
import pandas as pd
df = pd.read_csv("Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
x = df.drop('sales',axis=1)
y = df[["sales"]]

In [5]:
x.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [6]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [7]:
#Statsmodel ile modal kurmak

In [11]:
import statsmodels.api as sm

In [12]:
lm = sm.OLS(y,x)

In [14]:
model = lm.fit() # x ve y değerlerini tekrar yazamaya gerek yok

In [15]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 11 Mar 2023   Prob (F-statistic):                   2.43e-171
Time:                        14:03:35   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
##scikit learn ile model kurmak

In [17]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [18]:
model = lm.fit(x,y)

In [19]:
model.intercept_

array([2.93888937])

In [20]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# Tahmin
##### Sales = 2.94 + TV *. 004 + radio * 0.19 - newspaper*0.001

In [21]:
yeni_veri = [[30],[10],[40]] # 30 TV 10 Radio 40 gazete

In [22]:
yeni_veri = pd.DataFrame(yeni_veri).T

In [23]:
yeni_veri

0   1   2
0  30  10  40

In [25]:
model.predict(yeni_veri)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [28]:
from sklearn.metrics import mean_squared_error

In [31]:
tahmin=model.predict(x)

In [33]:
mse = mean_squared_error(y,tahmin)
mse

2.784126314510936

In [35]:
import numpy as np
np.sqrt(mse) # rmse

1.6685701407225697

# Model Tuning (Model Doğrulama)

In [36]:
#sınama seti
from sklearn.model_selection import train_test_split

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state= 99)

In [40]:
lm = LinearRegression()
model = lm.fit(x_train,y_train)

In [42]:
# train hatası
np.sqrt(mean_squared_error(y_train,model.predict(x_train)))

1.7236824822650754

In [43]:
#test hatası
np.sqrt(mean_squared_error(y_test,model.predict(x_test)))

1.4312783138301641

In [44]:
#k-fold cross validation
from sklearn.model_selection import cross_val_score


In [45]:
cross_val_score(model, x_train, y_train, cv =10, scoring = "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [49]:
# ortalama hata değeri (mse)
np.mean(-cross_val_score(model, x_train, y_train, cv =10, scoring = "neg_mean_squared_error"))

3.317028974234127

In [50]:
# ortalama hata değerin (rmse)
np.sqrt(np.mean(-cross_val_score(model, x_train, y_train, cv =10, scoring = "neg_mean_squared_error")))

1.821271252239525